### PR TITLE
Scripting and manage.py improvements

### PR DESCRIPTION
**Pull request by nippoo**
So far:

- Added python manage.py reset_db (should work, if it doesn't you need to make sure that the alyx user owns the database and schema:
```
ALTER SCHEMA public OWNER to alyx;
ALTER DATABASE alyx OWNER to alyx;
```
- Added python manage.py import_data (should be a cleaner way of importing data)

So far it's a bit hacky but should work. You might need to delete the imported google sheets file and let it repickle it.

### CODE REVIEW

**Comment by nippoo** [comment]
usage: `python manage.py reset_db && python manage.py import_data`

**Comment by nsteinme** [comment]
Have you tried it on rod yet?

**Comment by rossant** [comment]
What remains to be done in this PR?

**Comment by nippoo** [comment]
I'm just going to tidy this up today and and it'll be ready to merge in a few hours. I think I just want to move all code and commands into /misc/management/ with a user-specified DATA_DIR.

**Comment by nippoo** [comment]
Right, this one should be ready to merge now.

Usage: `python3 manage.py total_reset`
On rod: `python3 manage.py total_reset -P` (adds alyx_ro permissions, restarts apache2)

**Comment by rossant** [comment]
How to make it work locally to?

```
$ ./manage.py reset_db

You have requested a database reset.
This will IRREVERSIBLY DESTROY
ALL data in the database "alyx".
Are you sure you want to do this?
Type 'yes' to continue, or 'no' to cancel: yes
ERROR:root:Error: must be owner of schema public
Traceback (most recent call last):
  File "/home/cyrille/git/alyx/alyx/misc/management/commands/reset_db.py", line 83, in handle
    cursor.execute(drop_query)
psycopg2.ProgrammingError: must be owner of schema public

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cyrille/miniconda3/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/cyrille/miniconda3/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cyrille/miniconda3/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/cyrille/miniconda3/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/cyrille/git/alyx/alyx/misc/management/commands/reset_db.py", line 98, in handle
    cursor.execute(create_query)
psycopg2.ProgrammingError: schema "public" already exists
```

**Comment by nippoo** [comment]
As per my first post in this PR, you need to execute this as a database superuser first (one-time, then it will work forever)

```
ALTER SCHEMA public OWNER to alyx;
ALTER DATABASE alyx OWNER to alyx;
```

(replace the last word of each line with a different database user if it's not called 'alyx' (in my case it was 'labdb' for historical reasons))

**Comment by nippoo** [comment]
ps `reset_db` just wipes the database, you want `total_reset` if you want to reimport everything, and `total_reset -R` if you want to redownload Google Sheets

**Comment by nsteinme** [comment]
Could you write this all here: http://wiki.cortexlab.net/index.php/Alyx ?
Or somewhere in readthedocs, and point to it from that wiki page? We are
going to lose the ability to find this github thread eventually.

**Comment by nippoo** [comment]
Yep, can we merge this first?

**Comment by nippoo** [comment]
@rossant you happy to merge this? There are still a bunch of improvements it would be 'nice-to-have' at some later date but to be honest this is a perfectly usable starting point...

**Comment by rossant** [comment]
Yes I just wanted to try locally but to no avail so far :(

**Comment by rossant** [comment]
I'm using the user `cyrille` locally. I managed to create a `alyx` superuser. It still fails. What else should I do?

**Comment by nippoo** [comment]
OK so you need to log in as a superuser in a psql shell and:

```
\connect alyx
ALTER SCHEMA public OWNER to cyrille;
ALTER DATABASE alyx OWNER to cyrille;
```

**Comment by rossant** [comment]
I think there's a bug, the JSON fixtures should be loaded in order. Currently it seems like the order is arbitrary with `os.walk()` and it crashes. In the Makefile I used `manage.py loaddata ../data/json/*.json` to guarantee the order.

**Comment by nippoo** [comment]
Hmm, works fine for me and on rod, but I've added a `sorted()` in there just in case?

**Comment by rossant** [comment]
Thanks, that has fixed it! Merging.

**Pull request merged**
