### PR TITLE
Return 0 not None when not on water restriction

### PR DESCRIPTION
**Pull request by nippoo**

### CODE REVIEW

**Comment by rossant** [comment]
?? why `water_requirement_total` is defined twice now?

**Comment by nippoo** [comment]
woah whoops. yay automatically resolved merge conflicts

**Comment by nippoo** [comment]
really need to do #3 don't we...

**Comment by rossant** [comment]
yes! that's the most urgent thing on my list. I would not be comfortable with people starting to use Alyx until there is a well-covering testing suite and CI...

**Pull request merged**
