### PR TITLE
add zygosities rule for RCLcg

### PR DESCRIPTION
**Pull request by nsteinme**
@rossant added a new zygosity rule. Question: How will the new rule get propagated to existing mice?

### CODE REVIEW

**Comment by rossant** [comment]
At some point there was an update_zygosities script or command but I can't find it anymore?!

**Comment by rossant** [comment]
Something along the lines of this should work:

```python
from subjects.models import Subject, ZygosityFinder

zf = ZygosityFinder()
for subj in Subject.objects.all():
    zf.update_subject(subj)
```

To run in `./manage.py shell`.

**Comment by nsteinme** [comment]
Is it alyx/subjects/management/commands/update_zygosities.py
<https://github.com/cortex-lab/alyx/blob/37812c31bc57f6cfe2885d42019a9a44ba58501b/alyx/subjects/management/commands/update_zygosities.py>
?

How should we go about this - will this code get onto alyx-dev tonight so I
can try to run what you suggest tomorrow on alyx-dev? Thanks -

**Comment by rossant** [comment]
Ah, yes, thanks! So the code is already there, you just have to go on alyx-dev and do: `manage.py update_zygosities`.

**Comment by rossant** [comment]
A few minor style fixes to do:

```
./subjects/zygosities.py:50:26: E128 continuation line under-indented for visual indent
./subjects/zygosities.py:51:45: W291 trailing whitespace
```

Then we should be good to merge.

**Comment by nsteinme** [comment]
@rossant think I fixed this

**Comment by nsteinme** [comment]
Great, running update_zygosities worked on alyx-dev. Let me know when this
code goes onto the main server?

**Pull request merged**
