### PR TITLE
Better import

### PR DESCRIPTION
**Pull request by rossant**
Refactor the import script into `python data/importer.py`. Use JSON fixtures instead of migrations (so we may be able to get rid of all migrations?)

Three-steps process:

1. Download all data from the google sheets into a pickle file
2. Generate JSON fixtures from the google sheets data
3. Import the JSON fixtures with django loaddata

(1) is the longest to run. When the `dumped_google_sheets.pkl` file exists, this step is skipped which allows the import script to run faster (useful when debugging). Delete it and it will be downloaded the next time the import script is run.

Having JSON fixtures is also a nice "backup" of the data that is currently in the google sheets.

### CODE REVIEW

**Comment by rossant** [comment]
The procedure to rebuild the database is now:

* Make sure `data/json/` exists and contains `00-dumped-static.json`
* `make reset_all`: this command deletes and rebuilds all migrations files, downloads all data from the google spreadsheets if necessary, creates and imports the JSON fixtures.

**Comment by nsteinme** [comment]
I got the error below on the rmmigrations step, so I switched to trying to
run each of the reset_all components in sequence. It hung on the delete_all
step (on my computer I have to specify -U postgres for this to work, I'm
not sure how to get around that). Then I had to pip install pytz. But after
that it all worked - looks good!


$ make reset_all
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '*~' -exec rm -f {} +
find . -name '__pycache__' -exec rm -fr {} +
rm */migrations/*.py
rm: cannot remove '*/migrations/*.py': No such file or directory
make: *** [rmmigrations] Error 1

**Comment by nippoo** [comment]
btw - executing psql is a bit of a hacky way to do it and assumes that the db user is the same as the web user (this isn't the case on the server for example, for security reasons / separation of privileges).

better would be just using django_extensions which adds a manage.py reset_db command https://github.com/django-extensions/django-extensions

**Comment by rossant** [comment]
@nippoo is there a command to remove all tables in the database, but not removing the database itself (thus keeping the permissions)?

**Comment by nippoo** [comment]
hmm - you can 

```
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO alyx;
GRANT ALL ON SCHEMA public TO public;
```

But you do need to know the users for permissions.

This script does it a bit better since it at least fetches them from the settings.py file so it knows the credentials and dbname...: https://github.com/django-extensions/django-extensions/blob/af9f78c5935b61afaaadd2a989df2bddfab58f0b/django_extensions/management/commands/reset_db.py

reset_db doesn't work for me because for historical reasons I haven't called my database or username `alyx`. And when we move to using it in production I'll want to create a separate alyx-dev.cortexlab.net for example and it'll be very dangerous to be able to DROP DATABASE alyx; hardcoded into the script for obvious reasons!

**Comment by nippoo** [comment]
I'm getting:

```
django.db.utils.ProgrammingError: Problem installing fixture '/Users/nippoo/Development/alyx/alyx/../data/json/00-dumped-static.json': Could not load subjects.Species(pk=c8339f4f-4afe-49d5-b2a2-a7fc61389aaf): relation "subjects_species" does not exist
LINE 1: UPDATE "subjects_species" SET "json" = NULL, "binomial" = 'M...
               ^

make: *** [import_fixtures] Error 1
```

**Comment by nippoo** [comment]
Ah ignore me. I just ran `manage.py migrate` not the `make migrate` which specifies a whole bunch of explicit apps to migrate.

**Comment by nsteinme** [comment]
I tried to do this on rod but got this error:

nick@rod:/data/www/alyx/alyx$ sudo make reset_all
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '*~' -exec rm -f {} +
rm: cannot remove './actions/migrations~': Is a directory
rm: cannot remove './behavior/migrations~': Is a directory
rm: cannot remove './data/migrations~': Is a directory
rm: cannot remove './electrophysiology/migrations~': Is a directory
rm: cannot remove './equipment/migrations~': Is a directory
rm: cannot remove './imaging/migrations~': Is a directory
rm: cannot remove './misc/migrations~': Is a directory
rm: cannot remove './subjects/migrations~': Is a directory
make: *** [clean-pyc] Error 1

Cyrille did you try it on rod? Did I do something wrong? Thanks,

Nick

**Comment by rossant** [comment]
May be fixed now try again?

**Comment by nsteinme** [comment]
@nippoo sorry I forgot this, what username and password do I have to use to
do psql commands on rod? I can't get it to work, error below. I tried "sudo
make reset_all" and "su" (auth fail) and "su postgres" (auth fail) and "su
alyx" (no passwd entry for user alyx) and "su nick" (successful but didn't
clear the error). Thanks...

nick@rod:/data/www/alyx/alyx$ sudo make reset_all
psql -d postgres -c "DROP DATABASE alyx;" && psql -d postgres -c "CREATE
DATABASE alyx;"
psql: FATAL:  role "root" does not exist
make: *** [delete_all] Error 2

**Comment by rossant** [comment]
I think we may want to update the reset_all command to not drop the database, but just drop the tables in it. PR welcome...

**Comment by nsteinme** [comment]
@nippoo can we resolve this today? Some volunteers in the lab are trying to
test things out by adding their surgeries, but right now the website
version gives crashes for various things, I think just because it is in
some kind of limbo state in the middle of a failed import.

**Pull request merged**
