### PR TITLE
Backups

### LINKED ISSUE #24: Set up automatic backup
Is it possible to export database contents to google sheets? @kdharris101 and I were discussing that we'd like to have a "test switchover" period in which people enter things into the database but it's automatically exported to a google sheet so we have a backup/fallback (that's the same as the old system) in case alyx goes down or something. 

More generally, we need to have a good backup scheme, of course, for when we start using it seriously. I suppose this sort of thing is standard.

### PR DESCRIPTION
**Pull request by nsteinme**
Ok, here are SQL queries for three backups and a script that works for me to generate corresponding tsv files. I can open them in excel and it looks fine. 

Could you test this, let me know if there's anything to change about the approach? Then I'll write the other queries.

Closes #24

### CODE REVIEW

**Comment by nsteinme** [comment]
By the way these will totally break if we change things in the schema. We either need to be very aware of that, or develop a strategy to avoid it somehow, I don't know.

**Comment by nsteinme** [comment]
@rossant also, I'm not sure what to do to make the psql commands into an actual script, but anyway those three commands worked for me when executed from the command line. Let me know whether they work for you too.

**Comment by rossant** [comment]
I'm looking on it now. I'm making minor changes in the branch.

**Comment by nsteinme** [comment]
Yes, great, go for it.

**Comment by rossant** [comment]
OK I made some changes. Now all `.sql` files in the queries folder will run automatically. The tsv files are saved in `tsv_files`. I use the more portable `\ copy` option of psql for TSV export. I also added an header. I can open the files in Excel. Let me know if it works for you as well.

**Comment by nsteinme** [comment]
Looks good, I tested, works for me too. Will the cron be able to call it with an output_dir as an argument, for instance? This way it could provide a new folder with the day's date each day, for instance.

**Comment by rossant** [comment]
Sorry I thought it was a type with tsv :)
For the output dir I think it's better to implement the logic directly in the script, so in the script you set `output_dir` dynamically as a function of the date.

**Comment by rossant** [comment]
@nsteinme @nippoo should we hardcode the final path of the backups in the script before we merge this?  we can use ```DATE=`date +%Y-%m-%d` ```

**Comment by nsteinme** [comment]
Yes, I think they should go to //zserver/Data/alyx-backups/2017-02-28/*

I think on rod that'll be /mnt/zserver/Data/...

**Comment by rossant** [comment]
OK now you can do `./backup-tsv.sh /mnt/zserver/Data/` and it should save the backups where you want. Feel free to test it so I can merge. Then I guess you or Max could set up a cron already...

**Comment by nsteinme** [comment]
Works! I tried adding a cron on rod, we'll see whether it works. Will add
the other exports when I can.

**Pull request merged**
