### PR TITLE
Culling method

### PR DESCRIPTION
**Pull request by oliche**

### CODE REVIEW

**Comment by oliche** [comment]
Need to transform Cull method in FK or named integer field with the list of methods in 18-JUL-2019 Dawg meeting minutes:

From UK HO Schedule 1 Act (mice only):
-	Overdose of an anaesthetic
-	CO2
-	Dislocation of the neck
-	Concussion of the brain by striking the cranium
- 	Cooling followed by immersion in cold fixative (foetuses only)
-	Decapitation (foetuses only)
These may be accompanied by (referred to as ‘completing the method of killing):
Confirmation of permanent cessation of the circulation
Destruction of the brain
Dislocation of the neck
Exsanguination
Confirming the onset of rigor mortis
Instantaneous destruction of the body in a macerator.

**Comment by oliche** [comment]
The ending of a Water restriction in the save() of the subject when death date changes from null to something doesn't execute.
Need to move in the Cull create method

**Comment by GaelleChapuis** [comment]
After talking to UCL lab manager - Could we add 
-  perfusion
(even if technically it is a mixture of overdose + exanguination)?

**Comment by GaelleChapuis** [comment]
Added Perfusion as culling method

**Pull request merged**
