### PR TITLE
[WIP] Import data

### PR DESCRIPTION
**Pull request by rossant**

### CODE REVIEW

**Comment by nsteinme** [comment]
Looks great! Could you run it on the server version so I can check out the results? You can clear subjects_subject and actions_surgery first - nothing on there now is real data.

**Comment by rossant** [comment]
No it's not ready yet. At the moment I'm trying to make it work locally! Then I'd suggest you do the same on your local machine before we do it on the server. I have to wipe out the database entirely to make it work properly (it might be doable by deleting only specific tables but I didn't manage to do that yet). We can discuss this later but I think it would be better if we have a script that imports *everything* we need from an empty database. It's just easier and safer IMO.

**Comment by nsteinme** [comment]
Ok, two quick thoughts on that -

1) Maybe we should set up a test server ("alyxtest.cortexlab.net") so we
can continue to jointly test after going "live"?
2) Importing everything sounds fine, good plan, can we add the
species/strain/users/etc static tables from those datadump json files or
tsv already? Can discuss on call later.

**Comment by rossant** [comment]
1) why not but I think we'll need Max for that :)
2) already done in this PR! The static tables are imported from the json, and subjects, lines, and surgeries are imported straight from the latest version of the Google sheets. Will there be anything else to import?

**Comment by nsteinme** [comment]
I think that's it. We'll want to be careful to make sure I have all the
correct static tables before clearing anything though. There's a bunch of
weighing data in some mat files that I can add via rest API at some point,
plus of course experimental data, again coming via rest api where needed.

**Comment by rossant** [comment]
Note to self: this is the command to start from scratch and repopulate the data from the json dumps and the google sheets:

`psql -d postgres -c "DROP DATABASE alyx;" && psql -d postgres -c "CREATE DATABASE alyx;" && ./manage.py migrate`

**Pull request merged**
