### PR TITLE
Update to django 1.11

### LINKED ISSUE #231: Update to django 1.11
[Django 1.11 has just been released](https://docs.djangoproject.com/en/1.11/releases/1.11/). It is a Long Term Support release, contrary to 1.10 which we are currently using. Should we update before alyx starts being used in production? I don't think there will be many changes. @nippoo @nsteinme

### PR DESCRIPTION
**Pull request by rossant**
Closes #231

### CODE REVIEW

**Comment by rossant** [comment]
ready to merge @nippoo

**Comment by nippoo** [comment]
... that easy?!

**Comment by rossant** [comment]
As far as I can tell yes! The testing suite works and the admin interface seems to work.  But I didn't test anything with the REST API...

**Comment by rossant** [comment]
@nippoo shall we merge this? I suppose we need to update django to 1.11 on rod and try the admin interface and REST API?

**Pull request merged**
