### PR TITLE
add ai148 rules

### PR DESCRIPTION
**Pull request by nsteinme**
improbably, I was able to make a local copy of alyx using the pgdump .sql backup (yay! although this didn't 100% work because the genotype test results didn't all come through, not sure why, the messages all scroll by too fast to read any errors that there might be) and test this branch. It seems to work.

### CODE REVIEW

**Comment by rossant** [comment]
FYI here is what I use on cone to update alyx-dev from the backup:

```
cat alyx_full.sql | psql -q -U alyx_dev -h localhost -d alyx_dev
```

This command only works with sql backups starting from today. The backups need to be obtained with:

```
pg_dump -cOx -U alyx_ro -h localhost alyx > alyx_full.sql
```

**Comment by nsteinme** [comment]
Sounds good, thanks. I might try creating a local alyx from the
alyx_full.sql tomorrow again, then, just to check.

**Comment by rossant** [comment]
Looks like there is a style error (probably with spaces) -- do "flake8 ." in the alyx/alyx directory

**Comment by nsteinme** [comment]
"looks like there is a style error" <-- story of my life

Ok, I did that and I see this, do I have to fix all these things manually
or can it do it for me?

(alyx) C:\Users\Nick\Documents\GitHub\alyx\alyx>flake8
.\subjects\zygosities.py:93:1: E101 indentation contains mixed spaces and
tabs
.\subjects\zygosities.py:93:1: W293 blank line contains whitespace
.\subjects\zygosities.py:93:1: W191 indentation contains tabs
.\subjects\zygosities.py:94:1: W191 indentation contains tabs
.\subjects\zygosities.py:94:2: E131 continuation line unaligned for hanging
inde
nt
.\subjects\zygosities.py:94:44: W291 trailing whitespace
.\subjects\zygosities.py:95:1: E101 indentation contains mixed spaces and
tabs
.\subjects\zygosities.py:95:19: E128 continuation line under-indented for
visual
 indent
.\subjects\zygosities.py:95:38: W291 trailing whitespace
.\subjects\zygosities.py:98:48: W291 trailing whitespace
.\subjects\zygosities.py:99:28: E128 continuation line under-indented for
visual
 indent
.\subjects\zygosities.py:101:48: W291 trailing whitespace
.\subjects\zygosities.py:102:30: E128 continuation line under-indented for
visua
l indent

**Comment by rossant** [comment]
Try this:

```
pip install autopep8
autopep8 subjects/zygosities.py -i
```

**Comment by nsteinme** [comment]
k thanks done

**Pull request merged**
