### PR TITLE
updated formula for zyg from parent

### PR DESCRIPTION
**Pull request by nsteinme**
Here is the full set of possible cases that can be inputs to "_zygosity_from_parents", along with the correct answers. I tested the function in this commit and it produces all of these answers. Maybe we can make a unit test out of this, I guess? 

```
('+/+', '+/+') '+/+'
('+/+', '+/-') '+'
('+/+', '-/-') '+/-'
('+/+', '+') '+'
('+/+', None) '+/-'
('+/-', '+/+') '+'
('+/-', '+/-') None
('+/-', '-/-') None
('+/-', '+') None
('+/-', None) None
('-/-', '+/+') '+/-'
('-/-', '+/-') None
('-/-', '-/-') '-/-'
('-/-', '+') None
('-/-', None) '-/-'
('+', '+/+') '+'
('+', '+/-') None
('+', '-/-') None
('+', '+') None
('+', None) None
(None, '+/+') '+/-'
(None, '+/-') None
(None, '-/-') '-/-'
(None, '+') None
(None, None) '-/-'
```

### CODE REVIEW

**Comment by rossant** [comment]
Yes, I guess another possibility would be not to use a formula but to use this directly? This would be clearer, as efficient, and it wouldn't require a unit test. What do you think? 

Something like this (not tested):

```python
def _zygosity_from_parents(self, zm, zf):
    return {
        ('+/+', '+/+'): '+/+',
        ('+/+', '+/-'): '+',
        ('+/+', '-/-'): '+/-',
        ('+/+', '+'): '+',
        ('+/+', None): '+/-',
        ('+/-', '+/+'): '+',
        ('+/-', '+/-'): None,
        ('+/-', '-/-'): None,
        ('+/-', '+'): None,
        ('+/-', None): None,
        ('-/-', '+/+'): '+/-',
        ('-/-', '+/-'): None,
        ('-/-', '-/-'): '-/-',
        ('-/-', '+'): None,
        ('-/-', None): '-/-',
        ('+', '+/+'): '+',
        ('+', '+/-'): None,
        ('+', '-/-'): None,
        ('+', '+'): None,
        ('+', None): None,
        (None, '+/+'): '+/-',
        (None, '+/-'): None,
        (None, '-/-'): '-/-',
        (None, '+'): None,
        (None, None): '-/-',
        }.get((zm, zf), None)
```

**Comment by nsteinme** [comment]
You are in charge of style here :) Whatever seems best to you, go for it. I
don't have any objection to the version you propose -

**Comment by rossant** [comment]
OK, could you update and double-check that it works correctly?

**Comment by nsteinme** [comment]
Ok, I have implemented this function, I believe it works. I checked out this branch on alyx-dev and update_zygosities runs without errors now. 

1) Sorry but can you remind me if there's a way to run something so the flake problems are automatically corrected? (is there a reason this doesn't just happen anyway?? sorry but I don't have all the flake rules memorized....)

2) Do you know when this code will go onto the live alyx? 

3) Can we generate a list of all mice that got incorrect results under the old code? I think the best would be if a script like manage.py update_zygosities can go through and run the new function as well as the old one, and report any mice for which the results differ. I spoke with Charu about the bug and we thought that looking through this list of mice would be the best way to make sure there haven't been any critical mistakes related to it.

**Comment by rossant** [comment]
1. Have a look at https://github.com/hhatto/autopep8. Having a good and properly configured text editor allows you to avoid most flake errors. There are many possibilities but I use Sublime Text 3 with [this extension](https://github.com/dreadatour/Flake8Lint). You can also configure the text editor so that it automatically replaces all tabs by spaces, removes trailing whitespaces, etc.

2. On the next production update, Monday morning. I'll let you know.

3. Yes, I opened a new issue. To be clear, for each mouse, we determine the new zygosity computed by each version of the code (old and new) and we return those for which these zygosities differ?

**Comment by nsteinme** [comment]
Ok I installed the sublime extension, and I think I fixed the flake, we'll see. It looks like the extension tells you where you have flake errors but doesn't have an "auto fix" option, is that right? 

Re: 3, yes, exactly that!

**Comment by nsteinme** [comment]
hooray, I have passed the test...

**Pull request merged**
