### PR TITLE
[WIP] Raw SQL queries

### PR DESCRIPTION
**Pull request by rossant**

### CODE REVIEW

**Comment by rossant** [comment]
This is only a work-in-progress. It shouldn't be activated yet because it's probably a big security hole. It works but I suspect @nippoo is not going to like it. :) I guess we should find a better and relatively secure way of implementing this.

**Comment by nippoo** [comment]
Haha. This is excellent. Bit of a cheeky DROP TABLES; and you've lost everything including version history. 

So

1) http://stackoverflow.com/questions/26015851/django-rest-framework-passing-raw-query we should use DRF for this so it can be RESTFUL

2) we should make a separate user and somehow see if we can authenticate read-only. I don't think it's going to be easy to sanitise the raw SQL queries to make sure you don't put a `; DELETE` somewhere in your `SELECT` statement for example.

**Comment by rossant** [comment]
Closing for now: if we really need this feature (@nsteinme do you?) it shouldn't be implemented like this!

**Comment by nsteinme** [comment]
As long as the alyx_ro user still exists I think we're good.

**Pull request closed without merging**
